name: push image and push to dockerhub

on:
  push:
    branches: 
      - publish

env:
  DOCKERHUB_USERNAME: newbe36524
  DOCKERHUB_NAMESPACE: newbe36524
  ALIYUN_USERNAME: pianzide1117
  ALIYUN_NAMESPACE: newbe36524
  TENCENTYUN_USERNAME: 472158246
  TENCENTYUN_NAMESPACE: mcr_newbe36524
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: 
          - mcr.microsoft.com/dotnet/runtime:2.1,runtime:2.1
          - mcr.microsoft.com/dotnet/runtime:2.1.23,runtime:2.1.23
          - mcr.microsoft.com/dotnet/runtime:2.1.23-alpine3.12,runtime:2.1.23-alpine3.12
          - mcr.microsoft.com/dotnet/runtime:2.1.23-bionic,runtime:2.1.23-bionic
          - mcr.microsoft.com/dotnet/runtime:2.1.23-bionic-arm32v7,runtime:2.1.23-bionic-arm32v7
          - mcr.microsoft.com/dotnet/runtime:2.1.23-focal,runtime:2.1.23-focal
          - mcr.microsoft.com/dotnet/runtime:2.1.23-focal-arm32v7,runtime:2.1.23-focal-arm32v7
          - mcr.microsoft.com/dotnet/runtime:2.1.23-nanoserver-2009,runtime:2.1.23-nanoserver-2009
          - mcr.microsoft.com/dotnet/runtime:2.1.23-stretch-slim,runtime:2.1.23-stretch-slim
          - mcr.microsoft.com/dotnet/runtime:2.1.23-stretch-slim-arm32v7,runtime:2.1.23-stretch-slim-arm32v7
          - mcr.microsoft.com/dotnet/runtime:2.1-alpine,runtime:2.1-alpine
          - mcr.microsoft.com/dotnet/runtime:2.1-alpine3.12,runtime:2.1-alpine3.12
          - mcr.microsoft.com/dotnet/runtime:2.1-bionic,runtime:2.1-bionic
          - mcr.microsoft.com/dotnet/runtime:2.1-bionic-arm32v7,runtime:2.1-bionic-arm32v7
          - mcr.microsoft.com/dotnet/runtime:2.1-focal,runtime:2.1-focal
          - mcr.microsoft.com/dotnet/runtime:2.1-focal-arm32v7,runtime:2.1-focal-arm32v7
          - mcr.microsoft.com/dotnet/runtime:2.1-nanoserver-2009,runtime:2.1-nanoserver-2009
          - mcr.microsoft.com/dotnet/runtime:2.1-stretch-slim,runtime:2.1-stretch-slim
          - mcr.microsoft.com/dotnet/runtime:2.1-stretch-slim-arm32v7,runtime:2.1-stretch-slim-arm32v7
          - mcr.microsoft.com/dotnet/runtime:3.1,runtime:3.1
          - mcr.microsoft.com/dotnet/runtime:3.1.10,runtime:3.1.10
          - mcr.microsoft.com/dotnet/runtime:3.1.10-alpine3.12,runtime:3.1.10-alpine3.12
          - mcr.microsoft.com/dotnet/runtime:3.1.10-alpine3.12-arm64v8,runtime:3.1.10-alpine3.12-arm64v8
          - mcr.microsoft.com/dotnet/runtime:3.1.10-bionic,runtime:3.1.10-bionic
          - mcr.microsoft.com/dotnet/runtime:3.1.10-bionic-arm32v7,runtime:3.1.10-bionic-arm32v7
          - mcr.microsoft.com/dotnet/runtime:3.1.10-bionic-arm64v8,runtime:3.1.10-bionic-arm64v8
          - mcr.microsoft.com/dotnet/runtime:3.1.10-buster-slim,runtime:3.1.10-buster-slim
          - mcr.microsoft.com/dotnet/runtime:3.1.10-buster-slim-arm32v7,runtime:3.1.10-buster-slim-arm32v7
          - mcr.microsoft.com/dotnet/runtime:3.1.10-buster-slim-arm64v8,runtime:3.1.10-buster-slim-arm64v8
          - mcr.microsoft.com/dotnet/runtime:3.1.10-focal,runtime:3.1.10-focal
          - mcr.microsoft.com/dotnet/runtime:3.1.10-focal-arm32v7,runtime:3.1.10-focal-arm32v7
          - mcr.microsoft.com/dotnet/runtime:3.1.10-focal-arm64v8,runtime:3.1.10-focal-arm64v8
          - mcr.microsoft.com/dotnet/runtime:3.1.10-nanoserver-2009,runtime:3.1.10-nanoserver-2009
          - mcr.microsoft.com/dotnet/runtime:3.1-alpine,runtime:3.1-alpine
          - mcr.microsoft.com/dotnet/runtime:3.1-alpine3.12,runtime:3.1-alpine3.12
          - mcr.microsoft.com/dotnet/runtime:3.1-alpine3.12-arm64v8,runtime:3.1-alpine3.12-arm64v8
          - mcr.microsoft.com/dotnet/runtime:3.1-alpine-arm64v8,runtime:3.1-alpine-arm64v8
          - mcr.microsoft.com/dotnet/runtime:3.1-bionic,runtime:3.1-bionic
          - mcr.microsoft.com/dotnet/runtime:3.1-bionic-arm32v7,runtime:3.1-bionic-arm32v7
          - mcr.microsoft.com/dotnet/runtime:3.1-bionic-arm64v8,runtime:3.1-bionic-arm64v8
          - mcr.microsoft.com/dotnet/runtime:3.1-buster-slim,runtime:3.1-buster-slim
          - mcr.microsoft.com/dotnet/runtime:3.1-buster-slim-arm32v7,runtime:3.1-buster-slim-arm32v7
          - mcr.microsoft.com/dotnet/runtime:3.1-buster-slim-arm64v8,runtime:3.1-buster-slim-arm64v8
          - mcr.microsoft.com/dotnet/runtime:3.1-focal,runtime:3.1-focal
          - mcr.microsoft.com/dotnet/runtime:3.1-focal-arm32v7,runtime:3.1-focal-arm32v7
          - mcr.microsoft.com/dotnet/runtime:3.1-focal-arm64v8,runtime:3.1-focal-arm64v8
          - mcr.microsoft.com/dotnet/runtime:3.1-nanoserver-2009,runtime:3.1-nanoserver-2009
          - mcr.microsoft.com/dotnet/runtime:5.0,runtime:5.0
          - mcr.microsoft.com/dotnet/runtime:5.0.0,runtime:5.0.0
          - mcr.microsoft.com/dotnet/runtime:5.0.0-alpine3.12,runtime:5.0.0-alpine3.12
          - mcr.microsoft.com/dotnet/runtime:5.0.0-alpine3.12-amd64,runtime:5.0.0-alpine3.12-amd64
          - mcr.microsoft.com/dotnet/runtime:5.0.0-alpine3.12-arm64v8,runtime:5.0.0-alpine3.12-arm64v8
          - mcr.microsoft.com/dotnet/runtime:5.0.0-buster-slim,runtime:5.0.0-buster-slim
          - mcr.microsoft.com/dotnet/runtime:5.0.0-buster-slim-amd64,runtime:5.0.0-buster-slim-amd64
          - mcr.microsoft.com/dotnet/runtime:5.0.0-buster-slim-arm32v7,runtime:5.0.0-buster-slim-arm32v7
          - mcr.microsoft.com/dotnet/runtime:5.0.0-buster-slim-arm64v8,runtime:5.0.0-buster-slim-arm64v8
          - mcr.microsoft.com/dotnet/runtime:5.0.0-focal,runtime:5.0.0-focal
          - mcr.microsoft.com/dotnet/runtime:5.0.0-focal-amd64,runtime:5.0.0-focal-amd64
          - mcr.microsoft.com/dotnet/runtime:5.0.0-focal-arm32v7,runtime:5.0.0-focal-arm32v7
          - mcr.microsoft.com/dotnet/runtime:5.0.0-focal-arm64v8,runtime:5.0.0-focal-arm64v8
          - mcr.microsoft.com/dotnet/runtime:5.0.0-nanoserver-2009,runtime:5.0.0-nanoserver-2009
          - mcr.microsoft.com/dotnet/runtime:5.0-alpine,runtime:5.0-alpine
          - mcr.microsoft.com/dotnet/runtime:5.0-alpine3.12,runtime:5.0-alpine3.12
          - mcr.microsoft.com/dotnet/runtime:5.0-alpine3.12-amd64,runtime:5.0-alpine3.12-amd64
          - mcr.microsoft.com/dotnet/runtime:5.0-alpine3.12-arm64v8,runtime:5.0-alpine3.12-arm64v8
          - mcr.microsoft.com/dotnet/runtime:5.0-alpine-amd64,runtime:5.0-alpine-amd64
          - mcr.microsoft.com/dotnet/runtime:5.0-alpine-arm64v8,runtime:5.0-alpine-arm64v8
          - mcr.microsoft.com/dotnet/runtime:5.0-buster-slim,runtime:5.0-buster-slim
          - mcr.microsoft.com/dotnet/runtime:5.0-buster-slim-amd64,runtime:5.0-buster-slim-amd64
          - mcr.microsoft.com/dotnet/runtime:5.0-buster-slim-arm32v7,runtime:5.0-buster-slim-arm32v7
          - mcr.microsoft.com/dotnet/runtime:5.0-buster-slim-arm64v8,runtime:5.0-buster-slim-arm64v8
          - mcr.microsoft.com/dotnet/runtime:5.0-focal,runtime:5.0-focal
          - mcr.microsoft.com/dotnet/runtime:5.0-focal-amd64,runtime:5.0-focal-amd64
          - mcr.microsoft.com/dotnet/runtime:5.0-focal-arm32v7,runtime:5.0-focal-arm32v7
          - mcr.microsoft.com/dotnet/runtime:5.0-focal-arm64v8,runtime:5.0-focal-arm64v8
          - mcr.microsoft.com/dotnet/runtime:5.0-nanoserver-2009,runtime:5.0-nanoserver-2009
          - mcr.microsoft.com/dotnet/runtime:latest,runtime:latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: pull and sync
      run: |
        cd src/GithubActionGeneration
        pip install pipenv
        pipenv install
        pipenv run inv pull-image --data "${{ matrix.image }}"
        echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u $DOCKERHUB_USERNAME --password-stdin
        pipenv run inv docker-sync-dockerhub --data "${{ matrix.image }}"