name: push image and push to aliyun

on:
  push:
    branches: 
      - publish

env:
  DOCKERHUB_USERNAME: newbe36524
  DOCKERHUB_NAMESPACE: newbe36524
  ALIYUN_USERNAME: pianzide1117
  ALIYUN_NAMESPACE: newbe36524
  TENCENTYUN_USERNAME: 472158246
  TENCENTYUN_NAMESPACE: mcr_newbe36524
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: 
          - mcr.microsoft.com/dotnet/aspnet:2.1,aspnet:2.1
          - mcr.microsoft.com/dotnet/aspnet:2.1.23,aspnet:2.1.23
          - mcr.microsoft.com/dotnet/aspnet:2.1.23-alpine3.12,aspnet:2.1.23-alpine3.12
          - mcr.microsoft.com/dotnet/aspnet:2.1.23-bionic,aspnet:2.1.23-bionic
          - mcr.microsoft.com/dotnet/aspnet:2.1.23-bionic-arm32v7,aspnet:2.1.23-bionic-arm32v7
          - mcr.microsoft.com/dotnet/aspnet:2.1.23-focal,aspnet:2.1.23-focal
          - mcr.microsoft.com/dotnet/aspnet:2.1.23-focal-arm32v7,aspnet:2.1.23-focal-arm32v7
          - mcr.microsoft.com/dotnet/aspnet:2.1.23-stretch-slim,aspnet:2.1.23-stretch-slim
          - mcr.microsoft.com/dotnet/aspnet:2.1.23-stretch-slim-arm32v7,aspnet:2.1.23-stretch-slim-arm32v7
          - mcr.microsoft.com/dotnet/aspnet:2.1-alpine,aspnet:2.1-alpine
          - mcr.microsoft.com/dotnet/aspnet:2.1-alpine3.12,aspnet:2.1-alpine3.12
          - mcr.microsoft.com/dotnet/aspnet:2.1-bionic,aspnet:2.1-bionic
          - mcr.microsoft.com/dotnet/aspnet:2.1-bionic-arm32v7,aspnet:2.1-bionic-arm32v7
          - mcr.microsoft.com/dotnet/aspnet:2.1-focal,aspnet:2.1-focal
          - mcr.microsoft.com/dotnet/aspnet:2.1-focal-arm32v7,aspnet:2.1-focal-arm32v7
          - mcr.microsoft.com/dotnet/aspnet:2.1-stretch-slim,aspnet:2.1-stretch-slim
          - mcr.microsoft.com/dotnet/aspnet:2.1-stretch-slim-arm32v7,aspnet:2.1-stretch-slim-arm32v7
          - mcr.microsoft.com/dotnet/aspnet:3.1,aspnet:3.1
          - mcr.microsoft.com/dotnet/aspnet:3.1.10,aspnet:3.1.10
          - mcr.microsoft.com/dotnet/aspnet:3.1.10-alpine3.12,aspnet:3.1.10-alpine3.12
          - mcr.microsoft.com/dotnet/aspnet:3.1.10-alpine3.12-arm64v8,aspnet:3.1.10-alpine3.12-arm64v8
          - mcr.microsoft.com/dotnet/aspnet:3.1.10-bionic,aspnet:3.1.10-bionic
          - mcr.microsoft.com/dotnet/aspnet:3.1.10-bionic-arm32v7,aspnet:3.1.10-bionic-arm32v7
          - mcr.microsoft.com/dotnet/aspnet:3.1.10-bionic-arm64v8,aspnet:3.1.10-bionic-arm64v8
          - mcr.microsoft.com/dotnet/aspnet:3.1.10-buster-slim,aspnet:3.1.10-buster-slim
          - mcr.microsoft.com/dotnet/aspnet:3.1.10-buster-slim-arm32v7,aspnet:3.1.10-buster-slim-arm32v7
          - mcr.microsoft.com/dotnet/aspnet:3.1.10-buster-slim-arm64v8,aspnet:3.1.10-buster-slim-arm64v8
          - mcr.microsoft.com/dotnet/aspnet:3.1.10-focal,aspnet:3.1.10-focal
          - mcr.microsoft.com/dotnet/aspnet:3.1.10-focal-arm32v7,aspnet:3.1.10-focal-arm32v7
          - mcr.microsoft.com/dotnet/aspnet:3.1.10-focal-arm64v8,aspnet:3.1.10-focal-arm64v8
          - mcr.microsoft.com/dotnet/aspnet:3.1-alpine,aspnet:3.1-alpine
          - mcr.microsoft.com/dotnet/aspnet:3.1-alpine3.12,aspnet:3.1-alpine3.12
          - mcr.microsoft.com/dotnet/aspnet:3.1-alpine3.12-arm64v8,aspnet:3.1-alpine3.12-arm64v8
          - mcr.microsoft.com/dotnet/aspnet:3.1-alpine-arm64v8,aspnet:3.1-alpine-arm64v8
          - mcr.microsoft.com/dotnet/aspnet:3.1-bionic,aspnet:3.1-bionic
          - mcr.microsoft.com/dotnet/aspnet:3.1-bionic-arm32v7,aspnet:3.1-bionic-arm32v7
          - mcr.microsoft.com/dotnet/aspnet:3.1-bionic-arm64v8,aspnet:3.1-bionic-arm64v8
          - mcr.microsoft.com/dotnet/aspnet:3.1-buster-slim,aspnet:3.1-buster-slim
          - mcr.microsoft.com/dotnet/aspnet:3.1-buster-slim-arm32v7,aspnet:3.1-buster-slim-arm32v7
          - mcr.microsoft.com/dotnet/aspnet:3.1-buster-slim-arm64v8,aspnet:3.1-buster-slim-arm64v8
          - mcr.microsoft.com/dotnet/aspnet:3.1-focal,aspnet:3.1-focal
          - mcr.microsoft.com/dotnet/aspnet:3.1-focal-arm32v7,aspnet:3.1-focal-arm32v7
          - mcr.microsoft.com/dotnet/aspnet:3.1-focal-arm64v8,aspnet:3.1-focal-arm64v8
          - mcr.microsoft.com/dotnet/aspnet:5.0,aspnet:5.0
          - mcr.microsoft.com/dotnet/aspnet:5.0.0,aspnet:5.0.0
          - mcr.microsoft.com/dotnet/aspnet:5.0.0-alpine3.12,aspnet:5.0.0-alpine3.12
          - mcr.microsoft.com/dotnet/aspnet:5.0.0-alpine3.12-amd64,aspnet:5.0.0-alpine3.12-amd64
          - mcr.microsoft.com/dotnet/aspnet:5.0.0-alpine3.12-arm64v8,aspnet:5.0.0-alpine3.12-arm64v8
          - mcr.microsoft.com/dotnet/aspnet:5.0.0-buster-slim,aspnet:5.0.0-buster-slim
          - mcr.microsoft.com/dotnet/aspnet:5.0.0-buster-slim-amd64,aspnet:5.0.0-buster-slim-amd64
          - mcr.microsoft.com/dotnet/aspnet:5.0.0-buster-slim-arm32v7,aspnet:5.0.0-buster-slim-arm32v7
          - mcr.microsoft.com/dotnet/aspnet:5.0.0-buster-slim-arm64v8,aspnet:5.0.0-buster-slim-arm64v8
          - mcr.microsoft.com/dotnet/aspnet:5.0.0-focal,aspnet:5.0.0-focal
          - mcr.microsoft.com/dotnet/aspnet:5.0.0-focal-amd64,aspnet:5.0.0-focal-amd64
          - mcr.microsoft.com/dotnet/aspnet:5.0.0-focal-arm32v7,aspnet:5.0.0-focal-arm32v7
          - mcr.microsoft.com/dotnet/aspnet:5.0.0-focal-arm64v8,aspnet:5.0.0-focal-arm64v8
          - mcr.microsoft.com/dotnet/aspnet:5.0-alpine,aspnet:5.0-alpine
          - mcr.microsoft.com/dotnet/aspnet:5.0-alpine3.12,aspnet:5.0-alpine3.12
          - mcr.microsoft.com/dotnet/aspnet:5.0-alpine3.12-amd64,aspnet:5.0-alpine3.12-amd64
          - mcr.microsoft.com/dotnet/aspnet:5.0-alpine3.12-arm64v8,aspnet:5.0-alpine3.12-arm64v8
          - mcr.microsoft.com/dotnet/aspnet:5.0-alpine-amd64,aspnet:5.0-alpine-amd64
          - mcr.microsoft.com/dotnet/aspnet:5.0-alpine-arm64v8,aspnet:5.0-alpine-arm64v8
          - mcr.microsoft.com/dotnet/aspnet:5.0-buster-slim,aspnet:5.0-buster-slim
          - mcr.microsoft.com/dotnet/aspnet:5.0-buster-slim-amd64,aspnet:5.0-buster-slim-amd64
          - mcr.microsoft.com/dotnet/aspnet:5.0-buster-slim-arm32v7,aspnet:5.0-buster-slim-arm32v7
          - mcr.microsoft.com/dotnet/aspnet:5.0-buster-slim-arm64v8,aspnet:5.0-buster-slim-arm64v8
          - mcr.microsoft.com/dotnet/aspnet:5.0-focal,aspnet:5.0-focal
          - mcr.microsoft.com/dotnet/aspnet:5.0-focal-amd64,aspnet:5.0-focal-amd64
          - mcr.microsoft.com/dotnet/aspnet:5.0-focal-arm32v7,aspnet:5.0-focal-arm32v7
          - mcr.microsoft.com/dotnet/aspnet:5.0-focal-arm64v8,aspnet:5.0-focal-arm64v8
          - mcr.microsoft.com/dotnet/aspnet:latest,aspnet:latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        cd src/GithubActionGeneration
        pip install pipenv
        pipenv install
    - name: pull and sync
      run: |
        cd src/GithubActionGeneration
        pip install pipenv
        pipenv install
        pipenv run inv pull-image --data "${{ matrix.image }}"
        echo "${{ secrets.ALIYUN_TOKEN }}" | docker login -u $ALIYUN_USERNAME --password-stdin registry.cn-hangzhou.aliyuncs.com
        pipenv run inv docker-sync-aliyun --data "${{ matrix.image }}"