name: push image newbe36524_runtime_3.1-buster-slim

on:
  push:
    branches: 
      - develop

env:
  SOURCE_IMAGE_NAME: mcr.microsoft.com/dotnet/core/runtime:3.1-buster-slim 
  TARGET_IMAGE_NAME: newbe36524/runtime:3.1-buster-slim
  DOCKERHUB_USERNAME: newbe36524
  ALIYUN_USERNAME: pianzide1117
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Pull and push image
      run: |
        echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u $DOCKERHUB_USERNAME --password-stdin
        docker pull $SOURCE_IMAGE_NAME
        docker tag $SOURCE_IMAGE_NAME $TARGET_IMAGE_NAME
        docker push $TARGET_IMAGE_NAME
        echo "${{ secrets.ALIYUN_TOKEN }}" | docker login -u $ALIYUN_USERNAME --password-stdin registry.cn-hangzhou.aliyuncs.com
        docker pull $SOURCE_IMAGE_NAME
        docker tag $SOURCE_IMAGE_NAME registry.cn-hangzhou.aliyuncs.com/$TARGET_IMAGE_NAME
        docker push registry.cn-hangzhou.aliyuncs.com//$TARGET_IMAGE_NAME
